### ISSUE TITLE
fix-vf-meta: ttfont['name'] is returning NoneType and causing failure

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/gftools#108]
I'm using `fix-vf-meta` in a build script. 

```
$ gftools fix-vf-meta variable_ttf/EncodeSansSemiCondensedSC-VF.ttf
-----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/google-font-repos/Encode-Sans/virtualenv/bin/gftools-fix-vf-meta.py", line 335, in <module>
    main()
  File "/Users/stephennixon/type-repos/google-font-repos/Encode-Sans/virtualenv/bin/gftools-fix-vf-meta.py", line 326, in main
    fix_nametable(ttfont)
  File "/Users/stephennixon/type-repos/google-font-repos/Encode-Sans/virtualenv/bin/gftools-fix-vf-meta.py", line 120, in fix_nametable
    default_style = _get_vf_default_style(ttfont)
  File "/Users/stephennixon/type-repos/google-font-repos/Encode-Sans/virtualenv/bin/gftools-fix-vf-meta.py", line 206, in _get_vf_default_style
    return ttfont['name'].getName(name_id, 1, 0, 0).toUnicode()
AttributeError: 'NoneType' object has no attribute 'toUnicode'
```

In a similar (but slightly modified) case, I'm getting a seemingly similar error:

```
$ gftools fix-vf-meta variable_ttf/EncodeSansCondensed-Condensed-VF.ttf variable_ttf/EncodeSansCondensed-CondensedSC-VF.ttf
-----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/google-font-repos/Encode-Sans/virtualenv/bin/gftools-fix-vf-meta.py", line 335, in <module>
    main()
  File "/Users/stephennixon/type-repos/google-font-repos/Encode-Sans/virtualenv/bin/gftools-fix-vf-meta.py", line 322, in main
    ', '.join(map(os.path.basename, ttfonts))
  File "/Users/stephennixon/type-repos/google-font-repos/Encode-Sans/virtualenv/bin/../lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not TTFont
```

I've checked that my fontTools install is up to date:

```
$ pip install --upgrade fontTools
-----------------------------------------------------------------------
Requirement already up-to-date: fontTools in ./virtualenv/lib/python3.6/site-packages (3.35.2)
```
and then 
```
$ pip install --upgrade git+https://github.com/fonttools/fonttools --no-cache
```

...but I get the same errors.

## Reproduce

The repo at [4171164c](https://github.com/thundernixon/Encode-Sans/tree/4171164c81386856233808a888ec7dd2f99b1cfc) will (probably) reproduce this issue when you run:

```
sources/scripts/build-split-vf.sh -c
```

or 

```
sources/scripts/build.sh -split
```

If not, it may simply be a difference of FontTools installations.

**Comment by m4rc1e** [comment]
Thanks! will look into this today.

**Comment by anthrotype** [comment]
Platform 1 nameIDs (Macintosh) may not be present in the font (this one in particular looks like it went through pyftsubset which strips them by default unless one passes —name-legacy option).
I suggest you look for platform 3 (Windows) nameIDs, which almost always are present. And check if getName returns None, in which case try a different platform.

**Comment by m4rc1e** [comment]
I've updated fix-vf-meta and got Encode to build. I'll post issues to Encode now.

**Comment by thundernixon** [comment]
Thanks for the insight here! This makes much more sense, now.
