### ISSUE TITLE
add-font can't handle unknown weights (e.g. IBM Plex Sans "Text")

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/gftools#117]
Connected to but separate from #93, because this also matters for static fonts.

`add-font.py` is unable to successfully run on IBM Plex, unless the "Text" styles are temporarily removed from the directory. 

At minimum, we should consider adding "Text" as a known weight, though I think it might be useful if we could allow arbitrary style names, as Plex is definitely not the only typeface to have a non-standard style name.

The only reason I can see to _not_ have this functionality is if the `METADATA.pb` file is only useful to point out "standard" weights, aligning to the traditional `100–900` CSS weight range. However, [as MDN points out](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Values), in the CSS Level 4 font spec it is acceptable to specify any value font `font-weight`, from 1–1000. So, if we can't use this now, we will probably at least want to use it soon.

Current error when trying to add Plex:
```
$ gftools add-font /Users/stephennixon/type-repos/google-font-repos/fonts/ofl/ibmplexsans
------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/bin/gftools-add-font.py", line 269, in <module>
    app.run(main)
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/bin/gftools-add-font.py", line 255, in main
    metadata = _MakeMetadata(fontdir, is_new)
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/bin/gftools-add-font.py", line 116, in _MakeMetadata
    file_family_style_weights = _FileFamilyStyleWeights(fontdir)
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/bin/gftools-add-font.py", line 91, in _FileFamilyStyleWeights
    result = [fonts.FileFamilyStyleWeight(f) for f in files]
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/bin/gftools-add-font.py", line 91, in <listcomp>
    result = [fonts.FileFamilyStyleWeight(f) for f in files]
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/lib/python3.7/site-packages/gftools/util/google_fonts.py", line 464, in FileFamilyStyleWeight
    sw = StyleWeight(m.group(2))
  File "/Users/stephennixon/type-repos/google-font-repos/plex/venv/lib/python3.7/site-packages/gftools/util/google_fonts.py", line 448, in StyleWeight
    return ('normal', _KNOWN_WEIGHTS[styleweight])
KeyError: 'Text'
```

**Comment by thundernixon** [comment]
[The API doesn't currently support the Text style](https://github.com/google/fonts/pull/1837#issuecomment-460386999), so this issue is invalid.
