### ISSUE TITLE
add-fonts: pkg_resources.DistributionNotFound: The 'fs<3,>=2.2.0; extra == "ufo"'

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/gftools#118]
On a fresh virtual environment install of gftools (in editable mode, with the latest version from the master branch), I run into this error:

```
gftools add-fonts /Users/stephennixon/type-repos/google-font-repos/fonts/ofl/monoton
Traceback (most recent call last):
  File "/Users/stephennixon/Environments/gf/bin/gftools", line 4, in <module>
    __import__('pkg_resources').require('gftools==0.2.0')
  File "/Users/stephennixon/Environments/gf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/Users/stephennixon/Environments/gf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/Users/stephennixon/Environments/gf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/stephennixon/Environments/gf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/Users/stephennixon/Environments/gf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/stephennixon/Environments/gf/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fs<3,>=2.2.0; extra == "ufo"' distribution was not found and is required by fontTools
```

I've gotten past somewhat similar `pkg_resources.ContextualVersionConflict` errors by pip installing the specified missing version of a given dependency (e.g. `pip install Pillow==5.3.0`). However, it was difficult to understand what to install to solve this issue.

It ended up working when I installed `pip install fs[UFO]==2.2.0`. Actaully, I still got some errors, but after this, `add-font` was working as expected.

```
$ pip install fs[UFO]==2.2.0
--------------------------------------------------------------
Collecting fs[UFO]==2.2.0
  Using cached https://files.pythonhosted.org/packages/32/82/2dcee281d9e04039bbd72e48c42f27c5ef2f37f14880fbd9d9ba5826cf1b/fs-2.2.0-py2.py3-none-any.whl
  fs 2.2.0 does not provide the extra 'ufo'
Collecting pytz (from fs[UFO]==2.2.0)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting appdirs~=1.4.3 (from fs[UFO]==2.2.0)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /Users/stephennixon/Environments/gf/lib/python3.7/site-packages (from fs[UFO]==2.2.0) (40.7.3)
Requirement already satisfied: six~=1.10 in /Users/stephennixon/Environments/gf/lib/python3.7/site-packages (from fs[UFO]==2.2.0) (1.12.0)
Installing collected packages: pytz, appdirs, fs
Successfully installed appdirs-1.4.3 fs-2.2.0 pytz-2018.9
```

Wanted to document this, and how I got past it. I'm not completely sure whether this is an issue with gftools or with fontTools (or just with my computer). If anyone recommends that I post this issue to fontTools, I'm happy to. If this issue should be closed, please feel free to close it.

**Comment by simoncozens** [comment]
I think this is stale, but it's useful to have the report in case anyone else hits this!
