### ISSUE TITLE
add-font not ready for opsz naming

### ISSUE THREAD

**Issue by laerm0** [googlefonts/gftools#172]
It's saying pt size in the names isn't good (or, more precisely, is an error).

```
$ gftools add-font fonts/static
Traceback (most recent call last):
  File "/Users/stupakm/venvs/type-tools-py3/bin/gftools-add-font.py", line 267, in <module>
    app.run(main)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/stupakm/venvs/type-tools-py3/bin/gftools-add-font.py", line 253, in main
    metadata = _MakeMetadata(fontdir, is_new)
  File "/Users/stupakm/venvs/type-tools-py3/bin/gftools-add-font.py", line 115, in _MakeMetadata
    file_family_style_weights = _FileFamilyStyleWeights(fontdir)
  File "/Users/stupakm/venvs/type-tools-py3/bin/gftools-add-font.py", line 90, in _FileFamilyStyleWeights
    result = [fonts.FamilyStyleWeight(f) for f in files]
  File "/Users/stupakm/venvs/type-tools-py3/bin/gftools-add-font.py", line 90, in <listcomp>
    result = [fonts.FamilyStyleWeight(f) for f in files]
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/gftools/util/google_fonts.py", line 483, in FamilyStyleWeight
    return FileFamilyStyleWeight(path)
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/gftools/util/google_fonts.py", line 500, in FileFamilyStyleWeight
    weight = Weight(m.group(2))
  File "/Users/stupakm/venvs/type-tools-py3/lib/python3.7/site-packages/gftools/util/google_fonts.py", line 447, in Weight
    return _KNOWN_WEIGHTS[stylename]
KeyError: '10ptBold'
```

**Comment by davelab6** [comment]
@rsheeter how should people contributing fonts to /google/fonts generate METADATA files for VFs?

**Comment by rsheeter** [comment]
Why add-font the statics for what I assume based on mention of opsz is a variable font?

**Comment by laerm0** [comment]
Ah, well, I guess based on other issue chat currently happening, the statics aren't necessary, so this is not a concern anymore. 👍

**Comment by laerm0** [comment]
[whoops}
