### ISSUE TITLE
packager: fail to submit pr

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#238]
I'm trying to package and push [Vollkorn](https://github.com/FAlthausen/Vollkorn-Typeface) using the following command:

`gftools packager "Vollkorn" /my/google/fonts/path --no-source -p`

Everything works well, apart from when it attempts to make the pr, I get the following traceback

```
DONE Creating package for Vollkorn!
Start fetching yanone/master
Traceback (most recent call last):
  File "/Users/marcfoley/Type/tools/venv/bin/gftools-packager.py", line 144, in <module>
    packager.make_package(**args.__dict__)
  File "/Users/marcfoley/Type/tools/venv/lib/python3.8/site-packages/gftools/packager.py", line 1649, in make_package
    _packages_to_target(tmp_package_dir, family_dirs, target, is_gf_git,
  File "/Users/marcfoley/Type/tools/venv/lib/python3.8/site-packages/gftools/packager.py", line 1474, in _packages_to_target
    _packagage_to_git(tmp_package_family_dir, target, family_dir,
  File "/Users/marcfoley/Type/tools/venv/lib/python3.8/site-packages/gftools/packager.py", line 1382, in _packagage_to_git
    _git_make_commit(repo, add_commit, force, yes, quiet, branch,
  File "/Users/marcfoley/Type/tools/venv/lib/python3.8/site-packages/gftools/packager.py", line 1285, in _git_make_commit
    _git_fetch_master(repo, remote_name)
  File "/Users/marcfoley/Type/tools/venv/lib/python3.8/site-packages/gftools/packager.py", line 1773, in _git_fetch_master
    stats = remote.fetch(['refs/heads/master'], callbacks=PYGit2RemoteCallbacks())
  File "/Users/marcfoley/Type/tools/venv/lib/python3.8/site-packages/pygit2/remote.py", line 128, in fetch
    payload.check_error(err)
  File "/Users/marcfoley/Type/tools/venv/lib/python3.8/site-packages/pygit2/callbacks.py", line 93, in check_error
    check_error(error_code)
  File "/Users/marcfoley/Type/tools/venv/lib/python3.8/site-packages/pygit2/errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: unsupported URL protocol
```

It looks like it's attempting to fetch Yanone's repo `"Start fetching yanone/master"`. Since I manage this collection, I have a tonne of remotes, `git remote -v`:

```
asa	git@github.com:asantewa/fonts.git (fetch)
asa	git@github.com:asantewa/fonts.git (push)
bettergui	git@github.com:bettergui/fonts.git (fetch)
bettergui	git@github.com:bettergui/fonts.git (push)
eliheuer	git@github.com:eliheuer/fonts.git (fetch)
eliheuer	git@github.com:eliheuer/fonts.git (push)
kontur	git@github.com:kontur/fonts.git (fetch)
kontur	git@github.com:kontur/fonts.git (push)
micah	git@github.com:laerm0/fonts.git (fetch)
micah	git@github.com:laerm0/fonts.git (push)
mike	git@github.com:mjlagattuta/fonts.git (fetch)
mike	git@github.com:mjlagattuta/fonts.git (push)
mirko	git@github.com:bghryct/fonts.git (fetch)
mirko	git@github.com:bghryct/fonts.git (push)
origin	git@github.com:m4rc1e/fonts.git (fetch)
origin	git@github.com:m4rc1e/fonts.git (push)
thundernixon	git@github.com:thundernixon/fonts.git (fetch)
thundernixon	git@github.com:thundernixon/fonts.git (push)
upstream	git@github.com:google/fonts.git (fetch)
upstream	git@github.com:google/fonts.git (push)
yanone	git@github.com:yanone/fonts.git (fetch)
yanone	git@github.com:yanone/fonts.git (push)
```

I've read the packager docs and it seems to me that using `-p` means it will try and push to google/fonts by default.

**Comment by graphicore** [comment]
Ok, so we are maybe looking at two issues here:

1. a bug in `_find_github_remote` which returns the last remote it examined instead of the matched one. I fixed this.
2. `_pygit2.GitError: unsupported URL protocol` I can't reproduce!

I'm looking into another issue I just ran into but will commit the fix for 1. soon.
