### ISSUE TITLE
gftools-add-axis.py error

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#251]
I have trouble understanding how the add-axis script works, whatever I do I have this error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/gftools-add-axis.py", line 6, in <module>
    from gftools.axes_pb2 import AxisProto, FallbackProto
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gftools/axes_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

**Comment by graphicore** [comment]
Could be a dependency or version problem. Generally `axes_pb2.py` is a generated file.

`_descriptor` is imported in line 5 from `google.protobuf`

**Comment by RosaWagner** [comment]
Thanks! environment issue again
