### ISSUE TITLE
gftools packager possible bug preventing update a project

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/gftools#254]
When trying to create a new PR for a project that was recently pushed using Packager, different Key-Errors were reported.

Command used:
`gftools packager "Big Shoulders Display" ../fonts -p --no-source`

First attempt: KeyError: 'rokkit'
```
From https://github.com/google/fonts
 * branch              master     -> FETCH_HEAD
DONE fetch
Traceback (most recent call last):
  File "/Users/vv_monsalve/Documents/03_GOOGLE/fonts/venv/bin/gftools-packager.py", line 144, in <module>
    packager.make_package(**args.__dict__)
  File "/Users/vv_monsalve/Documents/03_GOOGLE/fonts/venv/lib/python3.8/site-packages/gftools/packager.py", line 1718, in make_package
    _packages_to_target(tmp_package_dir, family_dirs, target, is_gf_git,
  File "/Users/vv_monsalve/Documents/03_GOOGLE/fonts/venv/lib/python3.8/site-packages/gftools/packager.py", line 1543, in _packages_to_target
    _packagage_to_git(tmp_package_family_dir, target, family_dir,
  File "/Users/vv_monsalve/Documents/03_GOOGLE/fonts/venv/lib/python3.8/site-packages/gftools/packager.py", line 1443, in _packagage_to_git
    _git_make_commit(repo, add_commit, force, yes, quiet, branch,
  File "/Users/vv_monsalve/Documents/03_GOOGLE/fonts/venv/lib/python3.8/site-packages/gftools/packager.py", line 1354, in _git_make_commit
    title, body = _title_message_from_diff(repo, base_commit.tree, new_tree)
  File "/Users/vv_monsalve/Documents/03_GOOGLE/fonts/venv/lib/python3.8/site-packages/gftools/packager.py", line 1306, in _title_message_from_diff
    family_changes_dict = _get_change_info_from_diff(repo, root_tree, tip_tree)
  File "/Users/vv_monsalve/Documents/03_GOOGLE/fonts/venv/lib/python3.8/site-packages/gftools/packager.py", line 1261, in _get_change_info_from_diff
    family_tree = family_tree / pathpart
KeyError: 'rokkitt'
```

Second attempt: KeyError: 'capriola'
Third attempt: KeyError: 'bahiana'

**Comment by graphicore** [comment]
Ok, thanks, looks like its traversing a path that does not exist.

**Comment by graphicore** [comment]
This was interesting, I started to look into the issue and noticed that the tool wrongly merges "None" values from the stripped/normalized `upstream.yaml` values in google/fonts into the internal upstream configuration data. So, I fixed that, then continued to look into this issue. It turns out that was the root cause of this issue. :tada:
