### ISSUE TITLE
gftools builder and ttfautohint issue on BigSur

### ISSUE THREAD

**Issue by kosbarts** [googlefonts/gftools#298]
I am trying to generate fonts using the gftools builder config.yaml locally with my 
[https://github.com/kosbarts/Oi](https://github.com/kosbarts/Oi) project.

I install a venv and run the command from terminal but I get the following:
```
Traceback (most recent call last):
  File "/usr/local/bin/gftools-builder.py", line 17, in <module>
    from gftools.builder import GFBuilder
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gftools/builder/__init__.py", line 78, in <module>
    from ttfautohint.options import parse_args as ttfautohint_parse_args
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ttfautohint/__init__.py", line 13, in <module>
    from ttfautohint import memory
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ttfautohint/memory.py", line 18, in <module>
    raise OSError("Could not find the libc shared library")
OSError: Could not find the libc shared library
```
I have unistalled and reinstalled ttfautohint but the issue persists.
I also tried to disable autohinting with autohintTTF:false in the yaml file but the issue still persist.

Is this a system bug?
Any ideas?

**Comment by chrissimpkins** [comment]
https://github.com/fonttools/ttfautohint-py/issues/6

**Comment by simoncozens** [comment]
So until this is all fixed, we should not be unconditionally importing `ttfautohint`. Currently we import it even if the config file says not to autohint, which prevents Big Sur users using the builder at all.

**Comment by eliheuer** [comment]
Just in case a Big Sur user finds themselves confused here, I got gftools working on Big Sur 11.2 by installing [ttfautohint](https://www.freetype.org/ttfautohint/) manually, then `brew install libgit2`, and it works.
