### ISSUE TITLE
[packager] branch issue

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#324]
I have this traceback when I try to package this repo https://github.com/kosbarts/Oi

```
Cloning into bare repository '/var/folders/l4/8sp5y9ls3q3_dcyc6553lwcm0000gn/T/tmphfy8fnb6/repos/https_github_com_kosbarts_Oi__master'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
Upstream conf caused an error:
-----

Traceback (most recent call last):
  File "/Users/rosalie/env/lib/python3.7/site-packages/gftools/packager.py", line 1759, in make_package
    allow_build, yes, quiet, no_whitelist)
  File "/Users/rosalie/env/lib/python3.7/site-packages/gftools/packager.py", line 971, in _create_package_content
    , upstream_conf['branch'])
  File "/Users/rosalie/env/lib/python3.7/site-packages/gftools/packager.py", line 236, in _shallow_clone_git
    , stdout=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', '--depth', '1', '--bare', '-b', 'master', 'https://github.com/kosbarts/Oi', '/var/folders/l4/8sp5y9ls3q3_dcyc6553lwcm0000gn/T/tmphfy8fnb6/repos/https_github_com_kosbarts_Oi__master']' returned non-zero exit status 128.
```

the yaml looks like this:

```
name: Oi

repository_url: https://github.com/kosbarts/Oi

branch: master

category: DISPLAY

designer: Kostas Bartsokas

files:
    fonts/ttf/Oi-Regular.ttf : Oi-Regular.ttf
    OFL.txt : OFL.txt
```

**Comment by simoncozens** [comment]
Branch got renamed. Change `master` to `main` in the config.

**Comment by RosaWagner** [comment]
Ah yes true! I was searching on the upstream side, thks
