### ISSUE TITLE
gftools[qa] issues with cairo

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#407]
Managed to install everything on my new M1 BigSur, but having issues running gftools qa.

```
(env) MacBookeRosalie:variable rosalie$ gftools qa -f *.ttf --fontbakery
Traceback (most recent call last):
  File "/Users/rosalie/Google/env/bin/gftools-qa.py", line 47, in <module>
    from diffenator.diff import DiffFonts
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/diffenator/__init__.py", line 9, in <module>
    from cairo import Context, ImageSurface, FORMAT_A8, FORMAT_ARGB32
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: dlopen(/Users/rosalie/Google/env/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so, 2): Symbol not found: _cairo_append_path
  Referenced from: /Users/rosalie/Google/env/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/rosalie/Google/env/lib/python3.9/site-packages/cairo/_cairo.cpython-39-darwin.so

```

**Comment by simoncozens** [comment]
Same issue as this: https://github.com/pygobject/pycairo/issues/226
But that doesn't seem to have a good solution...

**Comment by simoncozens** [comment]
If you're going to move to anything in HTML reports, I'd recommend moving to SVG, animated by Javascript. Vharfbuzz has a method to render a Uharfbuzz buffer as SVG.

**Comment by m4rc1e** [comment]
I'm still quite fond of the current approach which uses the FreeType bitmaps. Perhaps allowing different backends would be a nice feature as well.

**Comment by RosaWagner** [comment]
Looks like it has been fixed !
