### ISSUE TITLE
Builder: `buildVariable` default should be smarter

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/gftools#416]
With the repo: https://github.com/eliheuer/rena, `gftools builder sources/config.yaml` with the below `config.yaml` fails:
```yaml
sources:
  - Rena.ufo
familyName: Rena
```
```console
$ gftools builder sources/config.yaml
Traceback (most recent call last):
  File "/Users/eli/Py/venvs/python3-venv-google-fonts/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/Users/eli/Py/venvs/python3-venv-google-fonts/lib/python3.9/site-packages/gftools/builder/__init__.py", line 178, in build
    self.build_variable()
  File "/Users/eli/Py/venvs/python3-venv-google-fonts/lib/python3.9/site-packages/gftools/builder/__init__.py", line 286, in build_variable
    self.gen_stat(ttFonts)
  File "/Users/eli/Py/venvs/python3-venv-google-fonts/lib/python3.9/site-packages/gftools/builder/__init__.py", line 346, in gen_stat
    self.config["axisOrder"] = [ax.axisTag for ax in varfonts[0]["fvar"].axes]
IndexError: list index out of range
```

**Comment by simoncozens** [comment]
`buildVariable` defaults to `true`. You can get around this error by manually setting it to `false` in your config file, but we should probably detect that a single UFO can't be variable.

**Comment by simoncozens** [comment]
Actually the proximate cause of the problem is that `build_variable` unconditionally calls `self.gen_stat(ttFonts)` even when no ttFonts were built. I'll fix both.

**Comment by eliheuer** [comment]
Setting `buildVariable` to `True` in `config.yaml` did work for me, thank you!
