### ISSUE TITLE
Error building some composite glyphs

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#432]
Problem building certain composites glyphs. I thought it was only the overlapping ones because, but in fact not. 

If I build with fontmake --> ok
If I build with builder 0.8.0 --> ok
If I build with Builder 0.8.2 --> error

Made a new glyphs files out of the UFO, and error glyphs is actually compatible, although ufo2glyphs tells me the features are different across ufo, which is curious.

**Test on Texturina** 
https://github.com/Omnibus-Type/Texturina
```
Traceback (most recent call last):
  File "/Users/rosalie/Google/env/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/gftools/builder/__init__.py", line 184, in build
    self.build_variable()
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/gftools/builder/__init__.py", line 292, in build_variable
    output_files = self.run_fontmake(source, args)
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/gftools/builder/__init__.py", line 329, in run_fontmake
    FontProject().run_from_glyphs(source, **args)
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 711, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/fontmake/font_project.py", line 974, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'Texturina.glyphs' -> 'master_ufo/Texturina.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'omacron'
```

**Test on Saira** (in anew venv to be sure there is no conflict with fontmake's dev branch)
https://github.com/Omnibus-Type/Saira
```
Traceback (most recent call last):
  File "/Users/rosalie/Google/envtest/bin/gftools-builder.py", line 83, in <module>
    builder.build()
  File "/Users/rosalie/Google/envtest/lib/python3.9/site-packages/gftools/builder/__init__.py", line 184, in build
    self.build_variable()
  File "/Users/rosalie/Google/envtest/lib/python3.9/site-packages/gftools/builder/__init__.py", line 292, in build_variable
    output_files = self.run_fontmake(source, args)
  File "/Users/rosalie/Google/envtest/lib/python3.9/site-packages/gftools/builder/__init__.py", line 329, in run_fontmake
    FontProject().run_from_glyphs(source, **args)
  File "/Users/rosalie/Google/envtest/lib/python3.9/site-packages/fontmake/font_project.py", line 711, in run_from_glyphs
    self.run_from_designspace(designspace_path, **kwargs)
  File "/Users/rosalie/Google/envtest/lib/python3.9/site-packages/fontmake/font_project.py", line 974, in run_from_designspace
    raise FontmakeError(
fontmake.errors.FontmakeError: In 'Saira.glyphs' -> 'master_ufo/Saira.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'Aring', 'Aringacute', 'Ldot', 'napostrophe', 'numero', 'ohorntilde', 'uhorntilde', 'underscoredbl'
```

**Comment by simoncozens** [comment]
It's working now!
