### ISSUE TITLE
Error in Diffenator

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#561]
```
INFO:gftools.qa:Running Diffenator
Traceback (most recent call last):
  File "/usr/local/bin/gftools-qa.py", line 263, in <module>
    main()
  File "/usr/local/bin/gftools-qa.py", line 240, in main
    qa.googlefonts_upgrade()
  File "/usr/local/lib/python3.9/site-packages/gftools/qa.py", line 216, in googlefonts_upgrade
    self.diffenator()
  File "/usr/local/lib/python3.9/site-packages/gftools/qa.py", line 108, in diffenator
    for style in self.matching_instances:
TypeError: 'NoneType' object is not iterable
```

on https://github.com/tallchai/akshar-type/blob/main/fonts/variable/Akshar%5Bwght%5D.ttf with latest Github version of gftools

**Comment by simoncozens** [comment]
Same as #495.
