### ISSUE TITLE
Builder crashing: cannot import name 'build_variations_ps_name' from 'axisregistry'

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#611]
Trying to build ReadexPro: https://github.com/RosaWagner/readexpro

```
Traceback (most recent call last):
  File "/Users/rosalie/Google/env/bin/gftools-builder.py", line 17, in <module>
    from gftools.builder import GFBuilder
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/gftools/builder/__init__.py", line 113, in <module>
    from gftools.fix import fix_font
  File "/Users/rosalie/Google/env/lib/python3.9/site-packages/gftools/fix.py", line 25, in <module>
    from axisregistry import (
ImportError: cannot import name 'build_variations_ps_name' from 'axisregistry' (/Users/rosalie/Google/env/lib/python3.9/site-packages/axisregistry/__init__.py)
```

**Comment by m4rc1e** [comment]
Works for me using latest gftools.

**Comment by RosaWagner** [comment]
I also has the latest version so I deleted my entire venv and reinstalled it, and after correcting some new glyph compatibility issue it worked :) Thanks for testing Marc
