### ISSUE TITLE
[gen-stat] AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by rsms** [googlefonts/gftools#614]
Repro

```
$ gftools --version
 o-o              o     o--o
o                 |     |            o
| o-o o-o o-o o-o o o-o o-o o-o o-o -o- o-o
o   | | | | | | | | |-' |   | | | |  |   \
 o-o  o-o o-o o-o o o-o o   o-o o o  o- o-o
                | Tools - Version 0.9.18
              o-o

Basic command examples:

    gftools compare-font font1.ttf font2.ttf
    gftools compare-font --help
    gftools --version
    gftools --help

gftools 0.9.18
$ mkdir stat
$ gftools gen-stat --out stat Inter-Roman.var.ttf Inter-Italic.var.ttf
Traceback (most recent call last):
  File "…/venv/bin/gftools-gen-stat.py", line 92, in <module>
    main()
  File "…/venv/bin/gftools-gen-stat.py", line 72, in main
    gen_stat_tables(fonts)
  File "…/venv/lib/python3.10/site-packages/gftools/stat.py", line 32, in gen_stat_tables
    build_stat(ttFont, siblings)
  File "…/venv/lib/python3.10/site-packages/axisregistry/__init__.py", line 169, in build_stat
    fallbacks_in_siblings = list(
  File "…/venv/lib/python3.10/site-packages/axisregistry/__init__.py", line 171, in <genexpr>
    axis_registry.fallbacks_in_name_table(f) for f in sibling_ttFonts
  File "…/venv/lib/python3.10/site-packages/axisregistry/__init__.py", line 115, in fallbacks_in_name_table
    + name_table.getBestSubFamilyName().split()
AttributeError: 'NoneType' object has no attribute 'split'
```

The two font files:

[Archive.zip](https://github.com/googlefonts/gftools/files/9648285/Archive.zip)

**Comment by m4rc1e** [comment]
Thanks Rasmus!

It seems your fonts are missing subfamily (nameID 2), typographic subfamily (nameID 17) names:

```PYTHON
>>> for r in f["name"].names:
...     print(r.nameID, r.toUnicode())
... 
4 Inter
6 Inter
270 Weight
271 Optical size
272 Thin
273 Extra Light
274 Light
275 Regular
276 Medium
277 Semi Bold
278 Bold
279 Extra Bold
280 Black
281 Display Thin
282 Display Extra Light
283 Display Light
284 Display Regular
285 Display Medium
286 Display Semi Bold
287 Display Bold
288 Display Extra Bold
289 Display Black
0 Copyright 2020 The Inter Project Authors
1 Inter
3 Inter:2022:17875920e
4 Inter
5 Version 4.000;git-17875920e
6 Inter
7 Inter UI and Inter is a trademark of rsms.
8 rsms
9 Rasmus Andersson
11 https://rsms.me/
12 https://rsms.me/
13 This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
14 http://scripts.sil.org/OFL
256 Open digits
257 Disambiguation
258 Disambiguation (no slashed zero)
259 tt ligatures
260 Alternate one
261 Open four
262 Open six
263 Open nine
264 Lower-case L with tail
265 Alternate German double s
266 Upper-case i with serif
267 Flat-top three
268 Capital G with spur
269 Single-storey a
270 Weight
271 Optical size
272 Thin
273 Extra Light
274 Light
275 Regular
276 Medium
277 Semi Bold
278 Bold
279 Extra Bold
280 Black
281 Display Thin
282 Display Extra Light
283 Display Light
284 Display Regular
285 Display Medium
286 Display Semi Bold
287 Display Bold
288 Display Extra Bold
289 Display Black
```

Our name builders require these nameIDs to be present so I'll add a better error msg or assertion.

**Comment by rsms** [comment]
Thanks Marc!
