### ISSUE TITLE
AttributeError: 'DFont' object has no attribute 'family_name'

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/gftools#678]
Hi!
Since I installed the last gftools version (0.9.29), when I try to run fontbakery `gftools qa -f *.ttf --fontbakery`, I get this error:
`AttributeError: 'DFont' object has no attribute 'family_name'`
Fontbakery version: 0.8.11

Any idea? @m4rc1e?

**Complete message:**

```
gftools qa -f *.ttf --fontbakery
Traceback (most recent call last):
  File "/Users/marichalemma/Google/env/bin/gftools", line 8, in <module>
    sys.exit(main())
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/scripts/__init__.py", line 91, in main
    mod.main(args[2:])
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/scripts/qa.py", line 188, in main
    family_name = family_name_from_fonts(dfonts)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/scripts/qa.py", line 45, in family_name_from_fonts
    results = set(f.family_name for f in fonts)
  File "/Users/marichalemma/Google/env/lib/python3.9/site-packages/gftools/scripts/qa.py", line 45, in <genexpr>
    results = set(f.family_name for f in fonts)
AttributeError: 'DFont' object has no attribute 'family_name'
```

**Comment by m4rc1e** [comment]
Try `pip install --upgrade diffenator2`

**Comment by emmamarichal** [comment]
Oh yes thanks, I missed this update!
