### ISSUE TITLE
gftools 0.9.34 fails when building a `.glyphspackage` file

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/gftools#722]
Building [this font](https://github.com/eliheuer/mebo) at commit [89601b6](https://github.com/eliheuer/mebo/tree/89601b6748bffd88815dcc1f0c54f585cbe23107) I get this error:
```
Traceback (most recent call last):
  File "/Users/eli/Py/venvs/GF-2023/bin/gftools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/gftools/scripts/__init__.py", line 91, in main
    mod.main(args[2:])
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/gftools/builder/__init__.py", line 668, in main
    builder = builder_class(**builder_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/gftools/builder/_ninja.py", line 24, in __init__
    super().__init__(**kwargs)
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/gftools/builder/__init__.py", line 163, in __init__
    self.fill_config_defaults()
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/gftools/builder/__init__.py", line 291, in fill_config_defaults
    self.config["buildVariable"] = self.determine_variability()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/gftools/builder/__init__.py", line 263, in determine_variability
    src = glyphsLib.GSFont(fp)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/glyphsLib/classes.py", line 4521, in __init__
    assert os.path.splitext(path)[-1] == ".glyphs", (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ('Please supply a file path to a .glyphs file',)
```

**Comment by eliheuer** [comment]
Nevermind, my `glyphsLib` was outdated. >_<
