### ISSUE TITLE
gftools fix-nonhinting error

### ISSUE THREAD

**Issue by weiweihuanghuang** [googlefonts/gftools#742]
When I tru to run the above on a ttf I get the following error:

```
/usr/local/bin/gftools:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import get_distribution
Traceback (most recent call last):
  File "/usr/local/bin/gftools-fix-nonhinting.py", line 54, in <module>
    from gftools.fix import fix_unhinted_font
  File "/usr/local/lib/python3.9/site-packages/gftools/fix.py", line 12, in <module>
    from gftools.utils import (
  File "/usr/local/lib/python3.9/site-packages/gftools/utils.py", line 30, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by weiweihuanghuang** [comment]
Was an installation error.
