### ISSUE TITLE
gftools packager error: Cannot set google.fonts_public.FamilyProto.primary_script to None

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/gftools#745]
I'm trying to onboard this: https://github.com/SorkinType/Agbalumo with `gftools packager "agbalumo" fonts -p`

And I keep getting this error, I think the main problem has to do with the primary script? 

I'm using gftools installed in editable mode @ commit [b074d8f](https://github.com/googlefonts/gftools/commit/b074d8fbb52631030e6c1f524513a5a2eb7b2d56)

```
10187 🔅 : gftools packager "agbalumo" fonts -p                                                                                                                      [~]
Font Family "agbalumo" not found on Google Fonts.
To add a new typeface family to Google Fonts we must know the license of the family.
It's very likely that OFL is the license that is expected here.
Your options [o]=OFL: SIL Open Font License,a=Apache License,u=Ubuntu Font License,q=quit program:o
temp file name is /var/folders/ht/8b6qb9pj7csc3pn8bgwwx3j80000gn/T/upstreamn1k3bi4i.yaml
Creating package with
----- upstream configuration (no comments, normalized) -----
name: agbalumo
repository_url: https://github.com/SorkinType/Agbalumo.git
archive:
branch: main
category:
- DISPLAY
classifications:
- DISPLAY
stroke:
designer: Raphael Alegbeleye
build:
files:
  OFL.txt: OFL.txt
  DESCRIPTION.en_us.html: DESCRIPTION.en_us.html
  fonts/ttf/Agbalumo-Regular.ttf: Agbalumo-Regular.ttf
------------------------------------------------------------
Cloning into bare repository '/var/folders/ht/8b6qb9pj7csc3pn8bgwwx3j80000gn/T/tmp05hq8zz2/repos/https_github_com_SorkinType_Agbalumo_git__main'...
remote: Enumerating objects: 141, done.
remote: Counting objects: 100% (141/141), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 141 (delta 62), reused 85 (delta 16), pack-reused 0
Receiving objects: 100% (141/141), 37.49 MiB | 20.17 MiB/s, done.
Resolving deltas: 100% (62/62), done.
Traceback (most recent call last):
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 702, in field_setter
    new_value = type_checker.CheckValue(new_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/google/protobuf/internal/type_checkers.py", line 198, in CheckValue
    raise TypeError(message)
TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eli/Py/venvs/GF-2023/bin/gftools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/eli/Google-Fonts/temp/gftools-main/gftools/Lib/gftools/scripts/__init__.py", line 91, in main
    mod.main(args[2:])
  File "/Users/eli/Google-Fonts/temp/gftools-main/gftools/Lib/gftools/scripts/add_font.py", line 318, in main
    metadata = _MakeMetadata(args, is_new)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eli/Google-Fonts/temp/gftools-main/gftools/Lib/gftools/scripts/add_font.py", line 173, in _MakeMetadata
    metadata.primary_script = script
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eli/Py/venvs/GF-2023/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 704, in field_setter
    raise TypeError(
TypeError: Cannot set google.fonts_public.FamilyProto.primary_script to None: None has type <class 'NoneType'>, but expected one of: (<class 'bytes'>, <class 'str'>)

Upstream conf caused an error:
-----

Traceback (most recent call last):
  File "/Users/eli/Google-Fonts/temp/gftools-main/gftools/Lib/gftools/packager.py", line 1672, in make_package
    family_dir = _create_package_content(tmp_package_dir, tmp_repos_dir,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eli/Google-Fonts/temp/gftools-main/gftools/Lib/gftools/packager.py", line 1049, in _create_package_content
    _create_or_update_metadata_pb(upstream_conf, package_family_dir,
  File "/Users/eli/Google-Fonts/temp/gftools-main/gftools/Lib/gftools/packager.py", line 893, in _create_or_update_metadata_pb
    raise e
  File "/Users/eli/Google-Fonts/temp/gftools-main/gftools/Lib/gftools/packager.py", line 880, in _create_or_update_metadata_pb
    subprocess.run(
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gftools', 'add-font', '/var/folders/ht/8b6qb9pj7csc3pn8bgwwx3j80000gn/T/tmp05hq8zz2/packages/ofl/agbalumo', '--github_url', 'https://github.com/SorkinType/Agbalumo.git']' returned non-zero exit status 1.
```

**Comment by eliheuer** [comment]
This will be fixed when this PR is merged: https://github.com/googlefonts/gftools/pull/746

Thanks Simon!
