### ISSUE TITLE
[manage traffic jam] error with last release

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/gftools#788]
@m4rc1e 

```
Traceback (most recent call last):
  File "/Users/rosalie/Google/env/bin/gftools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/rosalie/Google/env/lib/python3.11/site-packages/gftools/scripts/__init__.py", line 91, in main
    mod.main(args[2:])
  File "/Users/rosalie/Google/env/lib/python3.11/site-packages/gftools/scripts/manage_traffic_jam.py", line 233, in main
    if "lists" in args.filter:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Edit: command was `gftools manage-traffic-jam path/to/repo`

**Comment by m4rc1e** [comment]
What's the command you used?

**Comment by m4rc1e** [comment]
Ok, I've found the issue.
