### ISSUE TITLE
gftools fails

### ISSUE THREAD

**Issue by ollimeier** [googlefonts/gftools#830]
Hi there, 

I have a new Mac
I installed the the latest Python 3.12.1
and installed the latest gftools 0.9.47

I get the following error:

```
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_cffi_backend.cpython-312-darwin.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_cffi_backend.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_cffi_backend.cpython-312-darwin.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_cffi_backend.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.2/src/err/mod.rs:788:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/ollimeier/Documents/2024_BOM/Jobs/20240213_Fontwerk_Metabo/von_Fontwerk/Metabo/2_Production/work_fonts/01_font_post_production_metabo.py", line 19, in <module>
    from gftools.fix import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gftools/fix.py", line 12, in <module>
    from gftools.utils import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gftools/utils.py", line 27, in <module>
    from github import Github
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/github/__init__.py", line 51, in <module>
    from . import Auth
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/github/Auth.py", line 33, in <module>
    import jwt
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/cryptography/hazmat/_oid.py", line 7, in <module>
    from cryptography.hazmat.bindings._rust import (
pyo3_runtime.PanicException: Python API call failed
[Finished in 0.7s with exit code 1]
[cmd: ['/Library/Frameworks/Python.framework/Versions/3.12/bin/python3', '-u', '/Users/ollimeier/Documents/2024_BOM/Jobs/20240213_Fontwerk_Metabo/von_Fontwerk/Metabo/2_Production/work_fonts/01_font_post_production_metabo.py']]
[dir: /Users/ollimeier/Documents/2024_BOM/Jobs/20240213_Fontwerk_Metabo/von_Fontwerk/Metabo/2_Production/work_fonts]
[path: /Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin]
```

**Comment by ollimeier** [comment]
INFO: So, I was able to find a work around by using Python 3.11.0 instead of Python 3.12.1

**Comment by simoncozens** [comment]
Looks like this error comes from the `jwt` package, not gftools.

**Comment by simoncozens** [comment]
Sorry, pyca/cryptography. Could you (a) install `cryptography` in a new venv, (b) run

```
% python
>>> cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
```

and if it fails, report a bug in the pyca/cryptography repo with your installation environment? Thanks.

**Comment by m4rc1e** [comment]
@ollimeier what version of OS X are you running and do you gave dev tools installed? It works on my system with 3.12.

I think this may be related to https://github.com/googlefonts/gftools/issues/789

**Comment by simoncozens** [comment]
I'm guessing you've fixed this or found the downstream bug; will reopen if not.
