### ISSUE TITLE
gftools-add-font.py: fails to generate METADATA.pb

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/gftools#84]
I just tried running a variable font through gftools-add-font.py.

I get the following traceback:

```
Traceback (most recent call last):
  File "bin/gftools-add-font.py", line 267, in <module>
    app.run()
  File "/Users/marc/Documents/googlefonts/tools/env/lib/python2.7/site-packages/google/apputils/app.py", line 239, in run
    return _actual_start()
  File "/Users/marc/Documents/googlefonts/tools/env/lib/python2.7/site-packages/google/apputils/app.py", line 268, in _actual_start
    really_start()
  File "/Users/marc/Documents/googlefonts/tools/env/lib/python2.7/site-packages/google/apputils/app.py", line 221, in really_start
    sys.exit(main(argv))
  File "bin/gftools-add-font.py", line 253, in main
    metadata = _MakeMetadata(fontdir, is_new)
  File "bin/gftools-add-font.py", line 169, in _MakeMetadata
    var_axes = metadata.axes.add()
AttributeError: 'FamilyProto' object has no attribute 'axes'

```
The repo's [Protobuf](https://github.com/googlefonts/gftools/blob/master/Lib/gftools/fonts_public.proto) file doesn't have an axes field. I guess we need to sync them better.

**Comment by m4rc1e** [comment]
Solved in db355e4ff741194b6c80def4dfbcb1fe698c11f5
