### ISSUE TITLE
GF Builder Recipes issue: family renaming clash for variable fonts

### ISSUE THREAD

**Issue by arrowtype** [googlefonts/gftools#907]
My goal is to adjust the family name of two variable fonts, after building them with the GF Builder.

I’m using gftools `0.9.53`.

It seems like the new [Recipes](https://github.com/googlefonts/gftools/blob/0a9de342d19db5e7bcb164a55c2767a16e36d370/docs/gftools-builder/README.md#really-customizing-the-build-process) feature might be perfect for this, but I seem to be getting stuck on a syntax issue.

From the docs:

> If you add a `recipe` map and specify a `recipeProvider`, the recipe provider generates a recipe first, and your recipe is then overlaid on top of it, allowing you to customize certain targets or add additional ones.

This is what I’m attempting, but it isn’t working for me, just yet.

Here’s my config:

```yaml
familyName: Family Name
buildVariable: true
buildWebfont: false
outputDir: ./fonts
sources:
  - sources/ufo/FamilyNameRoman.designspace
  - sources/ufo/FamilyNameItalic.designspace
stat:
  - name: Width
    tag: wdth
    values:
      - name: Compressed
        value: 50
      - name: Extra Condensed
        value: 66
      - name: Condensed
        value: 82
      - name: Normal
        value: 100
        flags: 2
  - name: Weight
    tag: wght
    values:
      - name: Light
        value: 300
      - name: Regular
        value: 400
        flags: 2
      - name: Semi Bold
        value: 600
      - name: Bold
        value: 700
      - name: Black
        value: 900
recipeProvider: googlefonts
recipe:
  fonts/variable/FamilyNameRoman[wdth,wght].ttf
      - source: sources/ufo/FamilyNameRoman.designspace
      - operation: rename
        name: Family Name Variable
  fonts/variable/FamilyNameItalic[wdth,wght].ttf
      - source: sources/ufo/FamilyNameItalic.designspace
      - operation: rename
        name: Family Name Variable
```

And here’s the output I get:

```sh
Traceback (most recent call last):
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gftools/builder/__init__.py", line 46, in __init__
    strictyaml.load(config, BASE_SCHEMA)
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/parser.py", line 323, in load
    return generic_load(yaml_string, schema=schema, label=label)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/parser.py", line 292, in generic_load
    raise parse_error
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/parser.py", line 285, in generic_load
    document = ruamelyaml.load(yaml_string, Loader=DynamicStrictYAMLLoader)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/main.py", line 986, in load
    return loader._constructor.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/constructor.py", line 114, in get_single_data
    node = self.composer.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/composer.py", line 78, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/composer.py", line 143, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/composer.py", line 223, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/composer.py", line 141, in compose_node
    node = self.compose_sequence_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/composer.py", line 184, in compose_sequence_node
    while not self.parser.check_event(SequenceEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/parser.py", line 140, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/parser.py", line 538, in parse_block_sequence_first_entry
    return self.parse_block_sequence_entry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/parser.py", line 544, in parse_block_sequence_entry
    token.move_comment(self.scanner.peek_token())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/scanner.py", line 1810, in peek_token
    self._gather_comments()
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/scanner.py", line 1838, in _gather_comments
    self.fetch_more_tokens()
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/scanner.py", line 289, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/strictyaml/ruamel/scanner.py", line 664, in fetch_value
    raise ScannerError(
strictyaml.ruamel.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 38, column 15:
          - source: sources/ufo/FamilyNameRoman. ... 
                  ^ (line: 38)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stephennixon/.pyenv/versions/3.11.3/bin/gftools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gftools/scripts/__init__.py", line 91, in main
    mod.main(args[2:])
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gftools/builder/__init__.py", line 351, in main
    pd = GFBuilder(args.config)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephennixon/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gftools/builder/__init__.py", line 48, in __init__
    raise ValueError("Could not validate configuration") from e
ValueError: Could not validate configuration
```

I’ve tried to follow the docs as closely as possible, and I’ve tried several variations of config.yaml (for example, putting a hyphen in front of the variable font paths, which I think would be better...), but I haven’t cracked it yet. I’ve also tried adding the `--generate` flag to see whether that might help, but I get the same traceback.

If anyone has any insight as to what I might do differently to make this work, it would be greatly appreciated!

Thanks so much.

**Comment by simoncozens** [comment]
It's not your fault. I'm starting to get fed up with strictYAML; I think it's more trouble than it's worth. I might just rip it out or write our own config validator.

**Comment by arrowtype** [comment]
Hey Simon, thanks for your comment and reassurance! I can see why it's worth having the validator there, but yeah, that would be frustrating if it's resulting in a lot of issues like this one. 

Do you happen to see a way around this immediate problem, or is it too hard to say without seeing the full build context?

**Comment by arrowtype** [comment]
Okay, so the issue now with this recipe is that it seems like won’t work if I have `buildVariable` set to `true`, but it also won’t work if `buildVariable` is set to `false`. 

Basically, if variable fonts are building, it interprets the recipe as being a duplicate rule. But, if variable fonts aren’t building, then there is nothing to run the font rename script on.

How might I get past this?

Here’s the error for `buildVariable: true`:

```console
▶ make build FamilyName
Building fonts...

Building "FamilyName"...
ninja: error: build.ninja:448: multiple rules generate fonts/variable/FamilyNameRoman[wdth,wght].ttf

make: *** [build] Error 1
```

...but here’s the error for `buildVariable: false`:

```console
[9/202] rename
FAILED: fonts/variable/FamilyNameItalic[wdth,wght].ttf 
/gftools/bin/python -m gftools.builder.jobrunner gftools-rename-font -o 'fonts/variable/FamilyNameItalic[wdth,wght].ttf'  sources/ufo/FamilyNameItalic.designspace "Family Name Variable" 

Command failed:
gftools-rename-font -o fonts/variable/FamilyNameItalic[wdth,wght].ttf sources/ufo/FamilyNameItalic.designspace Family Name Variable

Traceback (most recent call last):
  File "/usr/local/bin/gftools-rename-font", line 8, in <module>
    sys.exit(main())
  File "/gftools/lib/python3.10/site-packages/gftools/scripts/rename_font.py", line 29, in main
    font = TTFont(args.font)
  File "/gftools/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 174, in __init__
    self.reader = SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/gftools/lib/python3.10/site-packages/fontTools/ttLib/sfnt.py", line 85, in __init__
    raise TTLibError("Not a TrueType or OpenType font (bad sfntVersion)")
fontTools.ttLib.TTLibError: Not a TrueType or OpenType font (bad sfntVersion)

[10/202] rename
FAILED: fonts/variable/FamilyNameRoman[wdth,wght].ttf 
/gftools/bin/python -m gftools.builder.jobrunner gftools-rename-font -o 'fonts/variable/FamilyNameRoman[wdth,wght].ttf'  sources/ufo/FamilyNameRoman.designspace "Family Name Variable" 

Command failed:
gftools-rename-font -o fonts/variable/FamilyNameRoman[wdth,wght].ttf sources/ufo/FamilyNameRoman.designspace Family Name Variable

Traceback (most recent call last):
  File "/usr/local/bin/gftools-rename-font", line 8, in <module>
    sys.exit(main())
  File "/gftools/lib/python3.10/site-packages/gftools/scripts/rename_font.py", line 29, in main
    font = TTFont(args.font)
  File "/gftools/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 174, in __init__
    self.reader = SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/gftools/lib/python3.10/site-packages/fontTools/ttLib/sfnt.py", line 85, in __init__
    raise TTLibError("Not a TrueType or OpenType font (bad sfntVersion)")
fontTools.ttLib.TTLibError: Not a TrueType or OpenType font (bad sfntVersion)
```

**Comment by simoncozens** [comment]
You started with a designspace, then renamed it, and said "that's how to produce a TTF". You want a `buildVariable` operation in there...

It's a good idea to start without the recipe, run `gftools-builder --generate` to show the default recipe, then tweak that.

**Comment by arrowtype** [comment]
Ah, yes, your explanation plus running `gftools-builder --generate` was very helpful! Thanks.

It was still somewhat confusing to figure out the ordering required for a successful STAT table (I think the `stat` information had to come after the recipe info to work), but I think I got there in the end.

Here’s the yaml I ended up with, in case it helps anyone:

```yaml
familyName: Family Name
buildVariable: false
buildWebfont: false
outputDir: ./fonts
sources:
  - sources/ufo/FamilyNameRoman.designspace
  - sources/ufo/FamilyNameItalic.designspace
recipeProvider: googlefonts
recipe:
  fonts/variable/FamilyNameRoman[wdth,wght].ttf:
    - source: sources/ufo/FamilyNameRoman.designspace
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildVariable
    - args: ""
      operation: fix
    - operation: rename
      name: Family Name Variable
  fonts/variable/FamilyNameItalic[wdth,wght].ttf:
    - source: sources/ufo/FamilyNameItalic.designspace
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildVariable
    - args: ""
      operation: fix
    - operation: rename
      name: Family Name Variable
    - args: ""
      needs:
        - ./fonts/variable/FamilyNameRoman[wdth,wght].ttf
      postprocess: buildStat
stat:
  - name: Width
    tag: wdth
    values:
      - name: Compressed
        value: 50
      - name: Extra Condensed
        value: 66
      - name: Condensed
        value: 82
      - name: Normal
        value: 100
        flags: 2
  - name: Weight
    tag: wght
    values:
      - name: Light
        value: 300
      - name: Regular
        value: 400
        flags: 2
      - name: Semi Bold
        value: 600
      - name: Bold
        value: 700
      - name: Black
        value: 900
```
