### ISSUE TITLE
builder: Can't visualize --graph

### ISSUE THREAD

**Issue by yanone** [googlefonts/gftools#908]
First off, `pydot` isn't found, so needs to be added to deps: `ModuleNotFoundError: No module named 'pydot'`

After installing it manually, I get this traceback:
```
Traceback (most recent call last):
  File "/Users/yanone/.pyenv/versions/3.11.1/bin/gftools", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/yanone/.pyenv/versions/3.11.1/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gftools/scripts/__init__.py", line 91, in main
    mod.main(args[2:])
  File "/Users/yanone/.pyenv/versions/3.11.1/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gftools/builder/__init__.py", line 361, in main
    pd.draw_graph()
  File "/Users/yanone/.pyenv/versions/3.11.1/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gftools/builder/__init__.py", line 329, in draw_graph
    graphs[0].write_png("graph.png")
  File "/Users/yanone/.pyenv/versions/3.11.1/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydot/core.py", line 1587, in new_method
    self.write(path, format=f, prog=prog, encoding=encoding)
  File "/Users/yanone/.pyenv/versions/3.11.1/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydot/core.py", line 1662, in write
    s = self.create(prog, format, encoding=encoding)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanone/.pyenv/versions/3.11.1/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydot/core.py", line 1762, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.
```

**Comment by simoncozens** [comment]
I don't want to add pydot to the dependencies for gftools, because it's really only used for niche cases. You worked out that you need to install it manually, which is good; the next step is `brew install graphviz` which will install the utilities which generate the actual graphs.
