### ISSUE TITLE
gftools-add-font.py: Needs documentation and usability improvements

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/gftools#92]
Myself and others are having trouble using `add-font.py`, it seems like this tool could use some refactoring and documentation. Marc has said the following to me regarding this tools: 

> frankly that should be sorted out before py3
> and it should be done with the GF eng team on board 

## Issue One
One issue I run into is needing gflags:

![screen shot 2018-10-19 at 12 04 39 pm](https://user-images.githubusercontent.com/5162664/47503265-ace09380-d837-11e8-942f-9e13146812df.png)

I have found that the python version works, `pip2 install python-gflags`

## Issue Two
I believe some of the paths are relative, this causes problems because the tool must be run from a specific directory, see below: 

![screen shot 2018-10-25 at 9 29 25 am](https://user-images.githubusercontent.com/5162664/47503593-8111dd80-d838-11e8-9074-778ba0c2d8ef.png)

**Comment by eliheuer** [comment]
I made a short video showing how to use this tool at this point in time: https://youtu.be/BTMPhh2737A

**Comment by davelab6** [comment]
> Issue One

Since `pip2 install python-gflags`, why not include `python-gflags` in `requirements.txt` and be done?

Perhaps because https://github.com/google/python-gflags is Py2 only? However, its README says that its been abandoned and progress happens in "abseil", and that is Py23 compatible per https://github.com/abseil/abseil-py/blob/181c8b334b87057d5dd32861f9708fb8ee66189e/setup.py#L33

So, include `absl-py` in `requirements.txt` and be done? :)

> Issue Two

If some of the paths are relative, what needs to be done to make the paths work from anywhere? :)

If you (@eliheuer) can make a PR that fixes this for you, then @nyshadhr9 or someone on the team can review that PR and let you know if your changes can be accepted into the google-internal "upstream" copy of the tool :)

**Comment by eliheuer** [comment]
Sounds good, I can try a PR.

This is an important tool and probably one of the first ones new users will try, so it should be easy to use from both py2 and py3.

**Comment by eliheuer** [comment]
We also need to add some documentation around using this with variable fonts: 

```
$ python2 bin/gftools-add-font.py ~/Google/fonts/ofl/kreon

Traceback (most recent call last):
...
  File "/Users/Air/Demo/gftools/Lib/gftools/util/google_fonts.py", line 446, in StyleWeight
    return ('normal', _KNOWN_WEIGHTS[styleweight])
KeyError: 'VF'
```

**Comment by felipesanches** [comment]
> We also need to add some documentation around using this with variable fonts:
> 
> ```
> $ python2 bin/gftools-add-font.py ~/Google/fonts/ofl/kreon
> 
> Traceback (most recent call last):
> ...
>   File "/Users/Air/Demo/gftools/Lib/gftools/util/google_fonts.py", line 446, in StyleWeight
>     return ('normal', _KNOWN_WEIGHTS[styleweight])
> KeyError: 'VF'
> ```

please open a new issue exclusively dedicated to the problem you just described in this comment

**Comment by eliheuer** [comment]
Ok, see issue #93

**Comment by davelab6** [comment]
Py23 will be important for this one especially because the upstream is py2

**Comment by anthrotype** [comment]
first time I hear about this abseil-py. I haven't read the docs yet, I'm just curious, what's the advantage over using plain vanilla `argparse`?

**Comment by davelab6** [comment]
> We also need to add some documentation around using this with variable fonts:

@nyshadhr9 already did something for that on the internal version, hopefully he can make a PR here to downstream it here :)

> what's the advantage 

gflags originated within Google, and is a widespread standard in-house instead of argparse.

Updating the imports to try gflags and on except then try abseil is fine, but its important that the public copy of the `add-font.py` tool here stays in sync with the internal version :)

**Comment by davelab6** [comment]
I had said,

> Py23 will be important for this one especially because the upstream is py2

But alas, @rsheeter says py23 isn't desirable for the upstream and `add-font.py` should remain py2 only for now (or, its not a big script, perhaps here we can have a downstream fork that is py3 only as `add-font-py3.py`? :)

**Comment by rsheeter** [comment]
Please don't fork it.

**Comment by davelab6** [comment]
Alright! :) So @eliheuer don't do that :) 

I think we should wait for @nyshadhr9 to downstream the VF support already written, and

**Comment by davelab6** [comment]
BUTTER FINGERS

The "need" here, AIUI, is that Eli has packaged gf-tools for PyPi on Python3, and Python2 only stuff won't go in that package, but that is how most people we want to use this stuff will be getting ahold of it. 

I think py23 is the ideal situation.

**Comment by rsheeter** [comment]
As far as I know the add_font tool is used by a very small population who can clone a github and run python 2 until we get around to updating all the tools. At some point we will but it is currently not a priority.

Am I missing something that makes this a big problem instead of the minor inconvenience I'm imagining it to be?

**Comment by eliheuer** [comment]
Ok, the PR is open. If anyone has suggestions on how this solution could be improved, please let me know. After I merge PR #105 I will close this issue.

**Comment by thundernixon** [comment]
Even though subset labels are working better than before, I still get quite a few errors along these lines ... For almost every family, I get the following when I run `add-font`:


```
no cp file for armenian found at /armenian_unique-glyphs.nam
no cp file for avestan found at /avestan_unique-glyphs.nam
no cp file for balinese found at /balinese_unique-glyphs.nam
no cp file for bamum found at /bamum_unique-glyphs.nam
no cp file for batak found at /batak_unique-glyphs.nam
no cp file for brahmi found at /brahmi_unique-glyphs.nam
no cp file for buginese found at /buginese_unique-glyphs.nam
no cp file for buhid found at /buhid_unique-glyphs.nam
no cp file for canadian-aboriginal found at /canadian-aboriginal_unique-glyphs.nam
no cp file for carian found at /carian_unique-glyphs.nam
no cp file for cham found at /cham_unique-glyphs.nam
no cp file for chakma found at /chakma_unique-glyphs.nam
no cp file for cherokee found at /cherokee_unique-glyphs.nam
no cp file for chinese-simplified found at /chinese-simplified_unique-glyphs.nam
no cp file for chinese-traditional found at /chinese-traditional_unique-glyphs.nam
no cp file for coptic found at /coptic_unique-glyphs.nam
no cp file for cuneiform found at /cuneiform_unique-glyphs.nam
no cp file for cypriot found at /cypriot_unique-glyphs.nam
no cp file for deseret found at /deseret_unique-glyphs.nam
no cp file for egyptian-hieroglyphs found at /egyptian-hieroglyphs_unique-glyphs.nam
no cp file for georgian found at /georgian_unique-glyphs.nam
no cp file for gothic found at /gothic_unique-glyphs.nam
no cp file for hanunoo found at /hanunoo_unique-glyphs.nam
no cp file for imperial-aramaic found at /imperial-aramaic_unique-glyphs.nam
no cp file for inscriptional-pahlavi found at /inscriptional-pahlavi_unique-glyphs.nam
no cp file for inscriptional-parthian found at /inscriptional-parthian_unique-glyphs.nam
no cp file for javanese found at /javanese_unique-glyphs.nam
no cp file for kaithi found at /kaithi_unique-glyphs.nam
no cp file for kayah-li found at /kayah-li_unique-glyphs.nam
no cp file for kharoshthi found at /kharoshthi_unique-glyphs.nam
no cp file for korean found at /korean_unique-glyphs.nam
no cp file for lepcha found at /lepcha_unique-glyphs.nam
no cp file for limbu found at /limbu_unique-glyphs.nam
no cp file for linear-b found at /linear-b_unique-glyphs.nam
no cp file for lisu found at /lisu_unique-glyphs.nam
no cp file for lycian found at /lycian_unique-glyphs.nam
no cp file for lydian found at /lydian_unique-glyphs.nam
no cp file for mandaic found at /mandaic_unique-glyphs.nam
no cp file for meetei-mayek found at /meetei-mayek_unique-glyphs.nam
no cp file for mongolian found at /mongolian_unique-glyphs.nam
no cp file for new-tai-lue found at /new-tai-lue_unique-glyphs.nam
no cp file for ol-chiki found at /ol-chiki_unique-glyphs.nam
no cp file for old-italic found at /old-italic_unique-glyphs.nam
no cp file for old-persian found at /old-persian_unique-glyphs.nam
no cp file for old-south-arabian found at /old-south-arabian_unique-glyphs.nam
no cp file for old-turkic found at /old-turkic_unique-glyphs.nam
no cp file for ogham found at /ogham_unique-glyphs.nam
no cp file for osmanya found at /osmanya_unique-glyphs.nam
no cp file for phags-pa found at /phags-pa_unique-glyphs.nam
no cp file for runic found at /runic_unique-glyphs.nam
no cp file for samaritan found at /samaritan_unique-glyphs.nam
no cp file for phoenician found at /phoenician_unique-glyphs.nam
no cp file for rejang found at /rejang_unique-glyphs.nam
no cp file for saurashtra found at /saurashtra_unique-glyphs.nam
no cp file for shavian found at /shavian_unique-glyphs.nam
no cp file for sundanese found at /sundanese_unique-glyphs.nam
no cp file for syloti-nagri found at /syloti-nagri_unique-glyphs.nam
no cp file for syriac-eastern found at /syriac-eastern_unique-glyphs.nam
no cp file for syriac-estrangela found at /syriac-estrangela_unique-glyphs.nam
no cp file for syriac-western found at /syriac-western_unique-glyphs.nam
no cp file for tagalog found at /tagalog_unique-glyphs.nam
no cp file for tagbanwa found at /tagbanwa_unique-glyphs.nam
no cp file for tai-le found at /tai-le_unique-glyphs.nam
no cp file for tai-tham found at /tai-tham_unique-glyphs.nam
no cp file for tai-viet found at /tai-viet_unique-glyphs.nam
no cp file for thaana found at /thaana_unique-glyphs.nam
no cp file for tibetan found at /tibetan_unique-glyphs.nam
no cp file for tifinagh found at /tifinagh_unique-glyphs.nam
no cp file for vai found at /vai_unique-glyphs.nam
no cp file for ugaritic found at /ugaritic_unique-glyphs.nam
no cp file for yi found at /yi_unique-glyphs.nam
```

Is this a separate issue, or the same?

**Comment by davelab6** [comment]
It's possible these files exist within Google and need to be published
upstream. Or they may not exist and need to be made.

**Comment by rsheeter** [comment]
Many don't exist.

**Comment by thundernixon** [comment]
Ah, that's helpful to know. Is it safe to say that for the existing fonts in the directory, these warnings can be ignored?

**Comment by davelab6** [comment]
Yeah if the fonts you are working on don't involve these subsets, then this
output can be ignored.

We should make all of them part of this report, though; I believe the ones
that exist inside Google are just cldr. Pyfontaine has some other language
definitions, if someone wants to contribute nam files :)

**Comment by thundernixon** [comment]
Because I'm running add-font on the whole google/fonts collection, I'm finding that at least one critical issue occurs from missing the codepoint file for korean: all the Korean fonts no longer have `subsets: "korean"` in their generated metadata files.

I'm seeing that there is no file like `korean_unique-glyphs.nam` at `Lib/gftools/encodings`. I'm curious about what the process was, and whether there might be a good source to start from if I or someone else were to add `korean_unique-glyphs.nam` to the gftools encodings directory. 

I see that Noto has [data related to cldr](https://github.com/googlei18n/nototools/tree/master/third_party/cldr), but I'm not finding anything obviously close to an glyph list for Korean.

On Pyfontaine there are [unicode subset lists](https://github.com/davelab6/pyfontaine/tree/master/fontaine/charsets/subsets) which appear to be where the gftools encodings were derived from.

Is it that I should run Pyfontaine on Noto Korean, and then transform this into `korean_unique-glyphs.nam`, or would that be off track and unnecessary (or would it even work as I'm thinking)? I have briefly tried setting it up and running it locally, but I've run into obstacles, and I figure I should know that it's actually a useful thing to do before I debug my setup.

**Comment by rsheeter** [comment]
Pretty sure there's an internal copy of a Korean nam, should just publish
it.

**Comment by rsheeter** [comment]
#127 updates nam files, including addition of korean

**Comment by thundernixon** [comment]
Nice, thanks!
